# Generated by Django 5.2.7 on 2025-12-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isShipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shippedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trackingNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
